"""
parser.py

Parses raw Groq responses (as returned by agent/llm_client.py's
LLMClient.call()) into a structured shape the rest of the agent can work
with: plain text reasoning, plus a list of requested tool calls.

This is where "LLM response parsing to extract tool calls and reasoning
traces" (Day 4, task 3) actually happens. Keeping it in its own module
means agent/core.py's control-flow logic never has to know the exact shape
of a raw groq.types.chat.ChatCompletion object -- it only ever sees
ParsedResponse.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class ToolCallRequest:
    """
    One tool call the LLM asked to make.

    `call_id` is Groq/OpenAI's tool_call id -- the subsequent tool-result
    message MUST reference this exact id (unlike Gemini, which matched
    function responses by name). It's generated by the LLM/API, not by us.
    """

    name: str
    args: Dict[str, Any]
    call_id: str


@dataclass
class ParsedResponse:
    """
    The result of parsing one LLM turn.

    `text` is the reasoning/answer text in this turn, if any (a turn can
    have text AND tool calls, though in practice Groq usually gives one or
    the other).
    `tool_calls` is every function call the LLM requested in this turn.
    """

    text: Optional[str]
    tool_calls: List[ToolCallRequest] = field(default_factory=list)

    @property
    def has_tool_calls(self) -> bool:
        return len(self.tool_calls) > 0

    def to_assistant_message(self) -> Dict[str, Any]:
        """
        Convert this parsed turn back into an OpenAI/Groq-compatible
        assistant message, ready to append to the running conversation
        history. Unlike the Gemini version of this project, there is no
        opaque signature to preserve -- reconstructing the message from
        its parsed fields is the standard, correct pattern for
        OpenAI-compatible tool use.
        """
        message: Dict[str, Any] = {"role": "assistant", "content": self.text}
        if self.tool_calls:
            message["tool_calls"] = [
                {
                    "id": call.call_id,
                    "type": "function",
                    "function": {"name": call.name, "arguments": json.dumps(call.args)},
                }
                for call in self.tool_calls
            ]
        return message


def parse_response(response: Any) -> ParsedResponse:
    """
    Parse a raw groq ChatCompletion response into a ParsedResponse.

    response.choices[0].message.content holds the text (or None).
    response.choices[0].message.tool_calls holds a list of requested tool
    calls, each with .id, and .function.name / .function.arguments (a JSON
    string that must be decoded).
    """
    message = response.choices[0].message

    tool_calls: List[ToolCallRequest] = []
    for raw_call in message.tool_calls or []:
        try:
            args = json.loads(raw_call.function.arguments)
        except json.JSONDecodeError:
            # A malformed arguments string should not crash the whole run --
            # treat it as an empty-args call and let the tool registry's
            # own validation surface a clear error for the missing fields.
            args = {}
        tool_calls.append(
            ToolCallRequest(name=raw_call.function.name, args=args, call_id=raw_call.id)
        )

    return ParsedResponse(text=message.content, tool_calls=tool_calls)


def parse_json_from_text(text: str) -> Optional[Any]:
    """
    Best-effort extraction of a JSON value from LLM output text.

    LLMs asked to "respond with ONLY a JSON array/object" occasionally
    still wrap it in markdown code fences or add a stray sentence before
    or after it. This strips common wrapping before falling back to a
    direct parse, and returns None (rather than raising) if nothing
    parseable is found -- callers are expected to handle that gracefully
    (e.g. by falling back to a single-task plan) rather than crashing the
    whole research run over a formatting slip.
    """
    if text is None:
        return None

    stripped = text.strip()

    # Strip a leading ```json / ``` fence and a trailing ``` fence, if present.
    fence_match = re.match(r"^```(?:json)?\s*(.*?)\s*```$", stripped, re.DOTALL)
    if fence_match:
        stripped = fence_match.group(1).strip()

    try:
        return json.loads(stripped)
    except json.JSONDecodeError:
        pass

    # Last resort: find the first '[' or '{' and the matching last ']' or '}'.
    for open_char, close_char in (("[", "]"), ("{", "}")):
        start = stripped.find(open_char)
        end = stripped.rfind(close_char)
        if start != -1 and end != -1 and end > start:
            candidate = stripped[start : end + 1]
            try:
                return json.loads(candidate)
            except json.JSONDecodeError:
                continue

    return None
